name: Weekly Maintenance

on:
  schedule:
    # Run at 03:00 JST (18:00 UTC) every Sunday
    - cron: '0 18 * * 0'
  workflow_dispatch:  # Allow manual trigger

jobs:
  maintenance:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run maintenance
      run: |
        python kkj_maintenance.py
    
    - name: Upload maintenance logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: maintenance-logs-${{ github.run_number }}
        path: |
          maintenance.log
        retention-days: 90