name: Weekly Maintenance

on:
  schedule:
    # Run at 03:00 JST (18:00 UTC) every Sunday
    - cron: '0 18 * * 0'
  workflow_dispatch:  # Allow manual trigger

jobs:
  maintenance:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create config file
      run: |
        # Create minimal config for maintenance
        python -c "
import json
config = {
    'database': {
        'path': 'kkj_search.db'
    }
}
with open('config.json', 'w') as f:
    json.dump(config, f, indent=2)
"
    
    - name: Run maintenance
      run: |
        python kkj_maintenance.py || echo "Maintenance completed with warnings"
    
    - name: Upload maintenance logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: maintenance-logs-${{ github.run_number }}
        path: |
          maintenance.log
          *.log
        if-no-files-found: warn
        retention-days: 90