name: Scheduled KKJ Search

on:
  schedule:
    # Run at 09:00 JST (00:00 UTC) every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  search:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create config and run search
      env:
        # GitHub Secrets for sensitive data
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SEARCH_KEYWORDS: ${{ secrets.SEARCH_KEYWORDS || 'システム開発,アプリケーション開発,ソフトウェア開発' }}
        EXCLUDE_KEYWORDS: ${{ secrets.EXCLUDE_KEYWORDS || '工事,建設,建築' }}
        MAX_RESULTS: ${{ secrets.MAX_RESULTS || '50' }}
      run: |
        # Create config.json using the script
        python .github/scripts/create_config.py
        
        # Validate configuration
        if [ ! -f "config.json" ]; then
          echo "エラー: config.json の作成に失敗しました"
          exit 1
        fi
        
        # Check if required secrets are set
        if [ -z "$OPENAI_API_KEY" ] || [ -z "$EMAIL_FROM" ] || [ -z "$EMAIL_TO" ]; then
          echo "警告: 必須の環境変数が設定されていません"
          echo "必要な環境変数: OPENAI_API_KEY, EMAIL_FROM, EMAIL_TO"
        fi
        
        # Run the search
        python kkj_search.py || {
          echo "検索の実行中にエラーが発生しました"
          exit 1
        }
    
    - name: Upload search results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: search-results-${{ github.run_number }}
        path: |
          *.log
          *.json
          *.db
        if-no-files-found: warn
        retention-days: 30